name: Remote SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          # update the script later
          script: |
            cd ~/actions-demo/frontend
            echo "Pulling latest changes from repository"
            git pull origin main
            npm install
            echo "Script executed successfully"
