name: Remote SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: 10.234.88.47
          username: ubuntu
          key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPH/aXKbvs/nMfjoHKI4XzMP96ICZ3OLSrEeBmgUYHQ9 ashabulraad@gmail.com
          port: 22
          # update the script later
          script: |
            cd ~/actions-demo/frontend
            echo "Pulling latest changes from repository"
            git pull origin main
            npm install
            echo "Script executed successfully"
