name: Sync

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Changes
        run: git pull
